on:
  push:
    tags-ignore:
      - '**'
    branches:
      - '**'

jobs:
  test:
    name: Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 16
          - 18
          - 19
          - 20
        os:
          - ubuntu-latest
          - windows-latest
        exclude:
          # I don't know and don't have energy to investigate why the tests fails,
          # but Node.js v16 support will end after few months, so I decided not to care.
          - os: windows-latest
            node-version: 16
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: TypeScript check
        run: pnpm run typecheck

      - name: Test
        run: pnpm test
