on:
  push:
    tags-ignore:
      - '**'
    branches:
      - '**'

jobs:
  test:
    name: Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 18
          - 20
          - 22
          - 23
        os:
          - ubuntu-latest
          # I don't know and don't have energy to investigate why the tests fails sometimes on Windows.
          # - windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: TypeScript check
        run: pnpm run typecheck

      - name: Test
        run: pnpm test
